name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi, Welcome to the technical writing mentorship program community!  We're so glad you took the time to report your' first issue"
        pr-message: "Hi, Wow, thanks for your awesome pull request! This is your first contribution to the technical writing mentorship program, and we're thrilled for your.' first pull request"
